services:
  weatherforecast:
    user: "1000:1000"
    ports:
      - 5125:5125
      - 8080:8080
      - 8081:8081
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;UserId=${DATABASE_USERNAME};Password=${DATABASE_PASSWORD};Database=postgres;
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy

  database:
    image: "postgres:18"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME} -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: