services:
  weatherforecast:
    user: "1000:1000"
    ports:
      - 1390:5125
    build:
      context: .
      dockerfile: WeatherForecast/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5125
      - ConnectionStrings__DefaultConnection=Server=db;Port=4737;User Id=${DATABASE_USERNAME};Password=${DATABASE_PASSWORD};
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: "postgres:18"
    user: "1000:1000"
    ports:
      - 4737:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    env_file:
     - .env
    volumes:
      - ${DATABASE_VOLUME_LOCATION}:/var/lib/postgresql


  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
    depends_on:
      - weatherforecast