services:
  weatherforecast:
    image: weatherforecast
    user: "1000:1000"
    ports:
      - 5125:5125
      - 8080:8080
      - 8081:8081
    build:
      context: .
      dockerfile: WeatherForecast/Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Host=database;Port=5432;Database=default_database;UserId=${DATABASE_USERNAME};Password=${DATABASE_PASSWORD};
    env_file:
      - .env
    depends_on:
      - database
  
  database:
    image: "postgres:18"
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: default_database
    env_file:
      - .env
    volumes:
      - ${DATABASE_VOLUME_LOCATION}:/var/lib/postgresql

