name: Deploy to Oskar home server

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: [self-hosted, oskar-home-server]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }}" >> .env
          echo "DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}" >> .env
          echo "DATABASE_VOLUME_LOCATION=${{ secrets.DATABASE_VOLUME_LOCATION }}" >> .env
          echo "CLOUDFLARE_TOKEN=${{ secrets.CLOUDFLARE_TOKEN }}" >> .env
      - name: Stop running containers
        run: docker compose down

      - name: Start containers
        run: docker compose -f ./docker-compose-prod.yaml up -d --build
